include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore
  # plugins: custom_lint は dev_dependencies から外したので一時的に無効化。
  # Phase 1 後半で再導入する。

linter:
  rules:
    # Style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true

    # Safety
    avoid_dynamic_calls: true
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    only_throw_errors: true

    # Doc
    public_member_api_docs: false
